# Generated by Django 4.2.10 on 2024-04-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='gallery')),
                ('date', models.DateField()),
                ('actors', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Horror', 'Horror'), ('Thriller', 'Thriller'), ('Action', 'Action'), ('Romance', 'Romance'), ('Comedy', 'Comedy'), ('Animated', 'Animated')], max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ('title',),
            },
        ),
    ]
